---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wang.
--- DateTime: 10/7/20 2:33 AM
---

NFT_DESTROY_ACCOUNT  = "1.2.265483"
ASSET_ACCEPT_ACCOUNT = "1.2.265483"
TEST_ACCOUNT = "1.2.265483"
PLAYERS_CONTRACT_ID   = "1.16.203"
TOKEN_CONTRACT_WHITE_LIST = {"1.16.203"}
WORLD_VIEW = "COCOS-JHQSJ"
TEST = false
VER = 1
function test() chainhelper:log('!- 3') end