---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wang.
--- DateTime: 10/7/20 2:45 AM
---
CONTRACT_NAME = "contract.jh-token-otc"
CONTRACT_CONFIGS = "contract.jh-configs"

local function _ContractConfig()
    if G_CONFIG == nil then
        G_CONFIG = import_contract(CONTRACT_CONFIGS)
    end
end

function _TransferOut(symbol_or_id, amount)
    _ContractConfig()
    assert(amount > 0, "#amount不正确!#")
    local auth = false
    -- 验证调用合约是否正确
    for i = 1,#G_CONFIG.OTC_TOKEN_CONTRACT_WHITE_LIST do
        if contract_base_info.invoker_contract_id == G_CONFIG.OTC_TOKEN_CONTRACT_WHITE_LIST[i] then
            auth = true
            break
        end
    end
    assert(auth,"#没有权限调用！#")
    chainhelper:adjust_lock_asset(symbol_or_id, -amount)
    chainhelper:transfer_from_owner(contract_base_info.caller, amount, symbol_or_id, true)
    
end

function _TransferIn(symbol_or_id, amount)
    assert(amount > 0, "#amount不正确!#")
    chainhelper:transfer_from_caller(contract_base_info.owner, amount, symbol_or_id, true)
    chainhelper:adjust_lock_asset(symbol_or_id, amount)
end


function TransferIn(symbol_or_id, amount)
    chainhelper:invoke_contract_function(CONTRACT_NAME, "_TransferIn", cjson.encode({
        { 2, { v = symbol_or_id } },
        { 1, { v = amount } }
    }))
end

function TransferOut(symbol_or_id, amount)
    chainhelper:invoke_contract_function(CONTRACT_NAME, "_TransferOut", cjson.encode({
        { 2, { v = symbol_or_id } },
        { 1, { v = amount } }
    }))
end

function test() chainhelper:log('!- 3') end