---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wang.
--- DateTime: 10/7/20 2:33 AM
---
-- NFT销毁账户
NFT_DESTROY_ACCOUNT  = "1.2.1254101"
-- 开发者接受账户
ASSET_ACCEPT_ACCOUNT = "1.2.1254103"
-- 社区接受账户
COMMUNITY_ACCEPT_ACCOUNT = "1.2.1254102"
-- 代币池账户
TOKEN_POOL_ACCOUNT = "1.2.1254100"
-- 测试账户
TEST_ACCOUNT = "1.2.29340"
-- 玩家接口合约
PLAYERS_CONTRACT_ID   = "1.16.205"
-- 白名单合约
TOKEN_CONTRACT_WHITE_LIST = {"1.16.205","1.16.211","1.16.214"}
-- 世界观
WORLD_VIEW = "COCOS-JHQSJ"
-- 农场NFT 世界观
FARMS_WORLD_VIEW = "COCOS-JHQSJ-FARMS"
-- 撮合市场世界观
MATCH_UP_WORLD_VIEW = "COCOS-JHQSJ-MATCH-UP"
-- 任务列表世界观
TASKS_WORLD_VIEW = "COCOS-JHQSJ-TASKS"
-- 开发者税收比例
DEV_DIVIDEND_RATE = 0.05
-- 社区税收比例
COMMUNITY_DIVIDEND_RATE = 0.03
-- 邀请者税收比例
GUIDE_DIVIDEND_RATE = 0.05
-- 分红代币
DIVIDEND_COINS = {"COCOS"}
-- 献祭
SACRIFICE_COINS = {
    DSC = 100000,
    CFS = 1000000,
    KKKK = 1500000,
    COCOS = 300000000,
    CVC = 400000000000,
}
-- 偷窃基础罚金 55COCOS
STEAL_FORFEIT = 5500000
-- 测试状态
TEST = true
-- 版本
VER = 1
function test() chainhelper:log('!- 3') end
